title: Guo-qing Jiang # your name (or website title) here
logo: "figures/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently a Assistant Research Scientist at Chinese Meteorology Bureau. Before that, I was a [KUAI](https://www.kuaishou.com) Tec. AI Algorithm Engineer working on understanding deep learning, face locallization, etc...
  <br><br>
#  I received my Ph.D degree of "Climate Sciences" at School of [Physics](http://www.phy.pku.edu.cn/) of [PekingUniversity](https://www.pku.edu.cn/) supervised by Prof. Jun Wei([page](http://www.atmos.pku.edu.cn/en/Faculty/Fulltimefaculty/64750.htm)). During my Ph.D career, I visited [EAPS](https://eapsweb.mit.edu/) of [MIT](http://www.mit.edu/) for one year, hosted by Prof. Paola Malanotte-Rizzoli([page](http://web.mit.edu/rizzoli/Public/)).
#  <br><br>
#  My research spans hurricane, climate, physical ocean and AI. I focus on theoritically understanding the generalization of deep learning and applying ML to climate-ocean and hurricane (typhoon) prediction problems. I enjoyed making applications of AI and ML on climate, physical ocean, natural disasters, and so on.
#  <br><br>
#  I work on a number of cross-projects in climate change, physic ocean, and CS. They usually involve coding in Python, Fortran and Pytorch. My detailed education and experience can be found in [LinkedIn](https://www.linkedin.com/in/guoqing-jiang-780a5bb2/).
#  <br><br>
  <a href="https://www.linkedin.com/in/guoqing-jiang-780a5bb2/">View My LinkedIn Profile</a>
  <a href="https://scholar.google.com/citations?user=kCBHjI4AAAAJ&hl=en">View My Google Scholar Profile</a>
  <a href="https://www.researchgate.net/profile/Guo_Qing_Jiang">View My Research Gate Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
